baseURL = 'http://localhost:1313/'
languageCode = 'en-US'
title = 'The Black Circle'
theme = 'the-black-circle'
enableRobotsTXT = true

[taxonomies]


[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true


[languages]

  [languages.en]
    contentDir = "content/en"
    title = "The Black Circle"
    weight = 10

  [languages.ar]
    contentDir = "content/ar"
    title = "الدائرة السوداء"
    weight = 20