[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
identifier = "Solutions"
name = "Solutions"
pageRef = "/solutions"
weight = 2

  # === Column 1: Financing ===
  [[main]]
  identifier = "Financing"
  parent = "Solutions"
  name = "Financing"
  pageRef = "/solutions/bitcoin-and-crypto-backed-lending"
  weight = 1

    [[main]]
    parent = "Financing"
    name = "Bitcoin-Backed Loans"
    pageRef = "/solutions/bitcoin-and-crypto-backed-lending"
    weight = 1


  # === Column 2: Investment ===
  [[main]]
  identifier = "Investment"
  parent = "Solutions"
  name = "Investment"
  pageRef = "/solutions/investment"
  weight = 2

    [[main]]
    parent = "Investment"
    name = "Trading"
    pageRef = "/solutions/investment/#trading"
    weight = 1

    [[main]]
    parent = "Investment"
    name = "Custody"
    pageRef = "/solutions/investment/#custody"
    weight = 2

    [[main]]
    parent = "Investment"
    name = "Bitcoin Yield Strategies"
    pageRef = "/solutions/investment/#yield-strategies"
    weight = 3


  # === Column 3: Wealth Planning ===
  [[main]]
  identifier = "Wealth Planning"
  parent = "Solutions"
  name = "Wealth Planning"
  pageRef = "/solutions/wealth-planning"
  weight = 3

    [[main]]
    parent = "Wealth Planning"
    name = "Insurance"
    pageRef = "/solutions/wealth-planning/#insurance"
    weight = 1

    [[main]]
    parent = "Wealth Planning"
    name = "Fiduciary Services"
    pageRef = "/solutions/wealth-planning/#fiduciary"
    weight = 2


  # === Column 4: Tailored Solutions ===
  [[main]]
  identifier = "Tailored Solutions"
  parent = "Solutions"
  name = "Tailored Solutions"
  pageRef = "/solutions/tailored-solutions"
  weight = 4

    [[main]]
    parent = "Tailored Solutions"
    name = "Visa & Relocation"
    pageRef = "/solutions/tailored-solutions/#visa-relocation"
    weight = 1

    [[main]]
    parent = "Tailored Solutions"
    name = "Bank Accounts"
    pageRef = "/solutions//tailored-solutions/#banking-access"
    weight = 2

    [[main]]
    parent = "Tailored Solutions"
    name = "Lifestyle"
    pageRef = "/solutions//tailored-solutions/#lifestyle"
    weight = 3

[[main]]
name = "The Origin"
pageRef = "/the-origin"
weight = 3

[[main]]
name = "Become A Client"
pageRef = "/request-access"
weight = 4

 ##############################
# Footer Menu Sitemap
##############################

[[footer]]
name = 'Home'
pageRef = '/'
weight = 1

[[footer]]
name = 'Solutions'
pageRef = '/solutions'
weight = 2

[[footer]]
name = 'The Origin'
pageRef = '/the-origin'
weight = 3

[[footer]]
name = 'Request Access'
pageRef = '/request-access'
weight = 4

 ##############################
# Footer Menu Terms
##############################

[[terms]]
name = 'Terms & Conditions'
pageRef = '/terms'
weight = 1

##############################
# Footer Menu Company
##############################

[[company]]
name = 'The Origin'
pageRef = '/the-origin'
weight = 3

##############################
# Footer Menu Products
##############################

[[products]]
name = "Financing"
pageRef = "/solutions/bitcoin-and-crypto-backed-lending"
weight = 4

[[products]]
name = "Investment"
pageRef = "/solutions/investment"
weight = 5

[[products]]
name = "Wealth Planning"
pageRef = "/solutions/wealth-planning"
weight = 6

[[products]]
name = "Tailored Solutions"
pageRef = "/solutions/tailored-solutions"
weight = 7


##############################
# Footer Menu Explore
##############################

[[explore]]
name = "Ultra-High-Net-Worth Individuals"
pageRef = "/solutions/uhnws"
weight = 1

[[explore]]
name = "Family Offices and Private Banks"
pageRef = "/solutions/private-bank-family-offices"
weight = 2

[[explore]]
name = "Crypto Institutions"
pageRef = "/solutions/crypto-native-organizations"
weight = 3